
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exrmsjbndkohexiureym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4cm1zamJuZGtvaGV4aXVyZXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTI4MDYsImV4cCI6MjA1ODM4ODgwNn0.g-HZIPtyFDKWnS5pcEXFUvkj_mz2GiOBYTf_TaE52yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
